[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = []
# Paths to ignore.
ignore = [
  "target/",
  "packages/stylist/target/",
  "packages/stylist-core/target/",

  "examples/benchmarks/target/",
  "examples/yew-integration/target/",
  "examples/yew-theme-agent/target/",
  "examples/yew-theme-yewdux/target/",
]

[tools]
wasm_bindgen = "0.2.77"
